pollApp/pages/urls.py
from django.urls import path

from . import views

app_name = 'pages'

urlpatterns = [
    path('',views.index,name = 'index')
]

pollApp/pollApp/urls.py
from django.contrib import admin
from django.urls import path,include
#include is to include another url file
urlpatterns = [
    path('polls/',include('polls.urls')),
    #as soon as we go to /polls/anthing the
    #we would look in the file polls.url
    path('',include('pages.urls')),
    path('admin/', admin.site.urls),

]

pollApp/polls/urls.py
from django.urls import path
from . import views 
#here we are giving this a namepace
#because we can also have other apps
app_name = 'polls'
urlpatterns = [
    path('',views.index,name = "index"),
    #the angle brackets are for the parameter
    #'' means just /polls if we did path("results",..)
    #that would mean/polls/results
    #also this would look in ./templates/index.html
    #but we are using global templates after changing the settings
    path('<int:question_id>',views.detail,name = "detail"),       
    #the above is only the question            
    path('<int:question_id>/results',views.results,name = "results")
    #the above is the details of the question
]

pollApp/pages/models.py
from django.db import models

# Create your models here.

pollApp/polls/models.py
from django.db import models

# Create your models here.
#this is where we add the database models
#there would be a primary key id made by default
class Question(models.Model):
    question_text = models.CharField(max_length = 200)
    pub_data = models.DateTimeField("date published")

    def __str__(self):
        return self.question_text

class Choice(models.Model):
    #when a question is deleted, then the choices are also deleted
    question = models.ForeignKey(Question,on_delete = models.CASCADE)
    choice_text = models.CharField(max_length = 200)
    votes = models.IntegerField(default = 0)

    def __str__(self):
        return self.choice_text

pollApp/pages/views.py
from django.shortcuts import render

def index(request):
    return render(request,'pages/index.html')

pollApp/polls/views.py
from .models import Question, Choice
from django.template import loader
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404,render
from django.urls import reverse

# Create your views here.
#get questions and display items
#the below url is being requested
def index(request):
    latest_question_list = Question.objects.all()
    print(len(latest_question_list),"this is the lenght")
    context = {"latest_question_list":latest_question_list}
    return render(request,'polls/index.html',context)

#show specific question and choices

def detail(request,question_id):
    try:
        question = Question.objects.get(pk = question_id)
    except Question.DoesNotExist :
        #raise an http error
        raise Http404("question does not exist")
    return render(request,'polls/detail.html',{"question":question})

#get questions and display results 

def results(request,question_id):
    question = get_object_or_404(Question,pk = question_id)
    return render(request,'polls/results.html',{'question':question})

pollApp/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>pollApp {% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body>
<div class="container">
    <div class="row">
        <div class="col-md">
            <div class="col-md-6 m-auto">
                {%block content%}{% endblock %}
            </div>
        </div>
    </div>
</div>
</body>
</html>

pollApp/templates/pages/index.html
{%extends 'base.html' %}
{% block content %}
<body>
    <a class="btn btn-dark" href="{% url 'polls:index' %}">View the polls</a>
</body>
{% endblock %}

pollApp/templates/polls/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    
</body>
</html>

pollApp/templates/polls/index.html
{% extends 'base.html'%}
{% block content %}
<h1 class="text-center mb-3">Poll Questions</h1>
    {% if latest_question_list %}
        {% for question in latest_question_list %}
            <div class="card mb-3">
                <div class="card-body">
                    <p class="lead">
                        <!-- we use this while outputting data from an object -->
                        {{ question.question_text }}
                    </p>
                    <!-- this polls:details and results is the namespace that we defined -->
                    <a href="{% url 'polls:detail' question.id %}" class = "btn btn-primary btn-sm">Vote Now</a>
                    <a href="{% url 'polls:results' question.id %}" class = "btn btn-secondary btn-sm">Results</a>
                </div>
            </div>
        {% endfor %}
    {% else %}
        <p>No polls available</p>
    {% endif %}
{% endblock %}

pollApp/templates/polls/results.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    
</body>
</html>